{
 "title": "Devpod / Nodes Overview",
 "tags": [ "devpod-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"}, cluster)"
    }
   },
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(kube_node_labels{cluster=~\"$cluster\"}, nodepool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$cluster: # of nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster (nodepool filter applied)",
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$cluster\", nodepool=~\"$nodepool\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average normalized load average(1min) per cluster",
   "type": "graph",
   "description": "Average of normalized load average across all nodes of a cluster. If the values is above 1, it means that the cluster is probably saturated.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(\n  node_load1{cluster=~\"$cluster\",}\n  /\n  count without (cpu) (\n    count without (mode) (\n      node_cpu_seconds_total * on(node) group_left() kube_node_labels{nodepool=~\"$nodepool\"}\n    )\n  )\n) by (cluster)\n",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current nodes with highest normalized load average (1min)",
   "type": "table-old",
   "description": "Top 10 nodes with highest normalized load average. Nodes with a high normalized load average do not represent a real problem, it only means that pods should probably not be scheduled to them.\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sort(\n  topk(10,\n    sum(\n      node_load1{cluster=~\"$cluster\"} * on(node) group_left(nodepool) kube_node_labels{nodepool=~\"$nodepool\"}\n      /\n      count without (cpu) (\n        count without (mode) (\n          node_cpu_seconds_total * on(node) group_left(nodepool) kube_node_labels{nodepool=~\"$nodepool\"}\n        )\n      )\n    ) by (node, nodepool, cluster)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Normalized Load average(1 min)",
   "type": "heatmap",
   "description": "Normalized load average per node, distributed in buckets. If the distribution is above 1, it means that our cluster is probably overbooked.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(\n  node_load1{cluster=~\"$cluster\",}\n  /\n  count without (cpu) (\n    count without (mode) (\n      node_cpu_seconds_total * on(node) group_left() kube_node_labels{nodepool=~\"$nodepool\"}\n    )\n  )\n) by (node, cluster)\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average free memory per cluster",
   "type": "graph",
   "description": "Average of free memory across all nodes of a cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n  node_memory_MemAvailable_bytes{cluster=~\"$cluster\"}\n  *\n  on(node, cluster) kube_node_labels{nodepool=~\"$nodepool\"}\n) by (cluster)\n",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current nodes with least available memory",
   "type": "table-old",
   "description": "Top 10 nodes with least amount of free memory. Ideally, we should never have a node with free memory equals to 0. Pods will start to get OOM killed.\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sort_desc(\n  bottomk(10,\n    sum(\n      node_memory_MemAvailable_bytes{cluster=~\"$cluster\"}\n      *\n      on(node, cluster) group_left(nodepool) kube_node_labels{nodepool=~\"$nodepool\"}\n    ) by (node, nodepool, cluster)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "heatmap",
   "description": "Free memory per node, distributed in buckets. Workspaces running on nodes in the lowest buckets are good candidates to get OOMed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{cluster=~\"$cluster\"}\n*\non(node, cluster) kube_node_labels{nodepool=~\"$nodepool\"}\n"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average free disk per cluster (/dev/sdb)",
   "type": "graph",
   "description": "Average of free disk space in the /dev/sdb across all nodes of a cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n  node_filesystem_avail_bytes{cluster=~\"$cluster\", fstype!=\"shiftfs\", device=\"/dev/sdb\"}\n  *\n  on(node, cluster) kube_node_labels{nodepool=~\"$nodepool\"}\n) by (device, cluster)\n",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current nodes with least available disk",
   "type": "table-old",
   "description": "Top 10 nodes with least amount of free space on the /dev/sdb mountpoint. If the any nodes have less than 20GB, it's time to clean it up. (Don't worry we have an alert for it)\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sort_desc(\n  bottomk(10,\n    sum(\n      node_filesystem_avail_bytes{cluster=~\"$cluster\", fstype!=\"shiftfs\", device=\"/dev/sdb\"}\n      *\n      on(node, cluster) group_left(nodepool) kube_node_labels{nodepool=~\"$nodepool\"}\n    ) by (node, nodepool, cluster)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "heatmap",
   "description": "Free disk space on /dev/sdb per node, distributed in buckets. Workspaces running on nodes in the lowest buckets will probably have issues.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{cluster=~\"$cluster\", fstype!=\"shiftfs\", device=\"/dev/sdb\"}\n*\non(node, cluster) kube_node_labels{nodepool=~\"$nodepool\"}\n"
    }
   ]
  }
 ]
}