packages:
  - name: all
    type: generic
    deps:
      - dev/image:docker
      - :dev-utils
  - name: all-app
    type: generic
    deps:
      - dev/blowtorch:app
      - dev/gpctl:app
      - dev/loadgen:app
      - dev/gp-gcloud:app
  - name: dev-utils
    type: docker
    deps:
      - dev/gpctl:app
      - dev/kubecdl:app
      - dev/gp-gcloud:app
    argdeps:
      - imageRepoBase
    config:
      buildArgs:
        VERSION: ${version}
      dockerfile: blazedock.Dockerfile
      image:
        - ${imageRepoBase}/dev-utils:${version}
        - ${imageRepoBase}/dev-utils:commit-${__git_commit}
  - name: "install"
    type: "generic"
    deps:
      - dev/gpctl:app
      - dev/kubecdl:app
      - dev/gp-gcloud:app
    config:
      commands:
        - [ "sh", "-c", "sudo mv dev-gpctl--app/gpctl /usr/local/bin/gpctl" ]
        - [ "sh", "-c", "sudo mv dev-kubecdl--app/kubecdl /usr/local/bin/kubecdl" ]
        - [ "sh", "-c", "sudo mv dev-gp-gcloud--app/gp-gcloud /usr/local/bin/gp-gcloud" ]

scripts:
  - name: preview
    description: Build Devpod, create a preview environment, and deploy to it
    script: ./preview/workflow/preview/preview.sh
  - name: prepare
    description: Prepare the repository for development
    script: |
      blazedock run dev:prepare-go dev:prepare-ts
  - name: prepare-go
    description: Prepare go packages
    script: |
      ./components/devpod-protocol/go/scripts/generate-config.sh
      blazedock exec --filter-type go -v -- go mod verify
  - name: prepare-ts
    description: Prepare typescript packages
    script: |
      yarn --network-timeout 100000 && yarn build
  - name: install-dev-utils
    description: Install dev-utils
    script: |
      blazedock build dev:install --dont-test --cache=remote-pull
