packages:
  - name: docker
    type: docker
    config:
      dockerfile: blazedock.Dockerfile
      buildArgs:
        VERSION: ${ipfsClusterVersion}
      image:
        - ${imageRepoBase}/ipfs/ipfs-cluster:${ipfsClusterVersion}
