name: Setup environment
description: "Setup environment"
inputs:
  identity_provider:
    description: "GCP workload identity provider"
    required: true
  service_account:
    description: "GCP service account"
    required: true
  blazedock_segment_key:
    description: "blazedock analytics key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "${{ inputs.identity_provider }}"
        service_account: "${{ inputs.service_account }}"
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        skip_install: true
    - id: env-vars
      name: configure env variables
      shell: bash
      run: |
        gcloud auth configure-docker ghcr.io --quiet

        {
            echo "BLAZEDOCK_SEGMENT_KEY=${{ inputs.blazedock_segment_key }}"
            echo "BLAZEDOCK_WORKSPACE_ROOT=$GITHUB_WORKSPACE"
        }  >> "$GITHUB_ENV"
