# Copyright (c) 2022 Devpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License.AGPL.txt in the project root for license information.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: workspace-monitoring-satellite-rules
spec:
  groups:
  - name: workspace-rules
    rules:
    - record: devpod_workspace_regular_not_active_percentage_mk2
      expr: |
        sum(devpod_ws_manager_mk2_workspace_activity_total{active="false"}) by (cluster) / sum(devpod_ws_manager_mk2_workspace_activity_total) by (cluster)

  - name: workspace-alerts
    rules:
    - alert: DevpodWorkspaceTooManyRegularNotActiveMk2
      labels:
        severity: critical
      for: 10m
      annotations:
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/DevpodWorkspaceRegularNotActive.md
        summary: too many running but inactive workspaces
        description: too many running but inactive workspaces. lower bound is 20 "regular not active" workspaces to reduce the false-positive rate.
      # bumped from 20 to 40 temporarily
      expr: |
        sum(devpod_workspace_regular_not_active_percentage_mk2) by(cluster) > 0.08
        AND
        sum (devpod_ws_manager_mk2_workspace_activity_total{active="false"}) by (cluster) > 40

    - alert: DevpodWorkspacesNotStartingMk2
      labels:
        severity: critical
      for: 10m
      annotations:
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/DevpodWorkspaceRegularNotActive.md
        summary: workspaces are not starting.
        description: inactive regular workspaces exists but workspaces are not being started.
      expr: |
        sum by(cluster) (avg_over_time(devpod_workspace_regular_not_active_percentage_mk2[1m]) > 0)
        AND
        sum by(cluster) (rate(devpod_ws_manager_mk2_workspace_startup_seconds_sum{type="Regular"}[1m])) == 0
    - alert: DevpodWsManagerMk2BackupFailureError
      labels:
        severity: error
        team: engine
      annotations:
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/WorkspaceBackupFailures.md
        summary: Workspace backups failed recently in cluster {{ $labels.cluster }}
        description: This can happen when a single node has failed in the cloud provider
      expr: |
        sum by (cluster) (increase(devpod_ws_manager_mk2_workspace_backups_failure_total{cluster!~"ephemeral.*"}[1h])) > 0
        AND
        sum by (cluster) (increase(devpod_ws_manager_mk2_workspace_backups_failure_total{cluster!~"ephemeral.*"}[1h])) < 16
    - alert: DevpodWsManagerMk2BackupFailureCritical
      labels:
        severity: critical
        team: engine
      annotations:
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/WorkspaceBackupFailures.md
        summary: Workspace backups failed recently in cluster {{ $labels.cluster }}
        description: This can be an indicator of two or more nodes failing in a cloud provider
      expr: |
        sum by (cluster) (increase(devpod_ws_manager_mk2_workspace_backups_failure_total{cluster!~"ephemeral.*"}[1h])) >= 16
