packages:
  - name: lib
    type: yarn
    srcs:
      - fixtures/**
      - src/**
      - package.json
      - tsconfig.json
    deps:
      - components/devpod-protocol:lib
      - components/public-api/typescript:lib
    config:
      packaging: library
      commands:
        # blazedock executes the build and test step in the wrong order, so we need to call a special script that builds before testing
        test: ["yarn", "test:blazedock"]
      yarnLock: ${coreYarnLockBase}/../yarn.lock
      tsconfig: tsconfig.json
