{
 "title": "Devpod / Component / ws-manager-bridge",
 "tags": [ "devpod-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"ws-manager-bridge\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"ws-manager-bridge.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"ws-manager-bridge.*\"}, pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Health Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workspace Instance events received (by both read/write replicas) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(devpod_ws_manager_bridge_workspace_instance_update_started_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "Events received"
    },
    {
     "expr": "sum(increase(devpod_ws_manager_bridge_workspace_instance_update_completed_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "Events completed"
    }
   ]
  },
  {
   "title": "Event processing lag by write replicas (started - completed events) [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(devpod_ws_manager_bridge_workspace_instance_update_started_total{cluster=~\"$cluster\", pod=~\"$pod\"}[10m])) - sum(increase(devpod_ws_manager_bridge_workspace_instance_update_completed_seconds_count{cluster=~\"$cluster\", pod=~\"$pod\"}[10m]))",
     "legendFormat": "# of events received - # of events completed"
    }
   ]
  },
  {
   "title": "Workspace instance updates completed by write replicas [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(devpod_ws_manager_bridge_workspace_instance_update_completed_seconds_count{outcome=\"success\"}[1m])) OR 0",
     "legendFormat": "success"
    },
    {
     "expr": "sum(increase(devpod_ws_manager_bridge_workspace_instance_update_completed_seconds_count{outcome=\"error\"}[1m])) OR 0",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Instances marked as stopped [5m]",
   "type": "timeseries",
   "description": "These are instances that are marked as stopped by ws-manager-bridge.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(devpod_ws_instances_marked_stopped_total[5m])) by (previous_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Updates Published", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Event updates by type published to Redis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(devpod_ws_manager_bridge_updates_published_total[1m])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Container image version",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "kube_pod_container_info{cluster=~\"$cluster\", pod=~\"$pod\", image=~\".+\", container=\"ws-manager-bridge\"}",
       "legendFormat": "{{cluster}} - {{image}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Cores being used"
      }
     ]
    },
    {
     "title": "CPU Saturation",
     "type": "graph",
     "description": "Saturation > 100% means that the container is requesting more than its limits.\n\nKubernetes will start to throttle CPU when that happens. That's a sign of degraded performance.\n\n'No Data' indicates that the pod has no CPU limits.",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\"}\n) by (pod, cluster, node)\n",
       "legendFormat": "{{cluster}} - {{node} - {{pod}} - CPU Saturation"
      },
      {
       "expr": "sum(\nrate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod)",
       "legendFormat": "{{pod}} - CPU Throttles"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Saturation",
     "type": "graph",
     "description": "Memory can't be throttled. When a container reaches 100% of its memory limits,  Kubernetes will kill the container and restart it.\n\n'No Data' indicates that the pod doesn't have Memory limits.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\nrate(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\", resource=\"memory\"}\n) by (pod, cluster, node)\n",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Memory Saturation"
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
      },
      {
       "expr": "sum (\n  rate(container_network_transmit_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
      }
     ]
    },
    {
     "title": "Network Saturation (Packets Dropped)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum (\n  rate(container_network_receive_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Receive"
      },
      {
       "expr": "sum (\n  rate(container_network_transmit_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "Errors/s" }
     ],
     "targets": [
      {
       "expr": "sum (\n  rate(container_network_receive_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
      },
      {
       "expr": "sum (\n  rate(container_network_transmit_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
       "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{cluster}} - {{kubernetes_pod_node_name}} - {{pod}} "
      }
     ]
    },
    {
     "title": "Pod Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_running{cluster=~\"$cluster\", pod=~\"$pod\"} == 1 ",
       "legendFormat": "{{pod}}  - RUNNING"
      },
      {
       "expr": "(\n  sum by (pod) (kube_pod_container_status_terminated{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
       "legendFormat": "{{pod}}  - TERMINATED -> {{reason}}"
      },
      {
       "expr": "(\n  sum by (pod) (kube_pod_container_status_waiting{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
       "legendFormat": "{{pod}}  - WAITING -> {{reason}}"
      }
     ]
    },
    {
     "title": "Replicas availability",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{cluster=~\"$cluster\", deployment=\"ws-manager-bridge\"}",
       "legendFormat": "{{cluster}} - {{deployment}} - Desired"
      },
      {
       "expr": "kube_deployment_status_replicas_available{cluster=~\"$cluster\", deployment=\"ws-manager-bridge\"}",
       "legendFormat": "{{cluster}} - {{deployment}} - Available replicas"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{cluster=~\"$cluster\", deployment=\"ws-manager-bridge\"}",
       "legendFormat": "{{cluster}} - {{deployment}} - Unvailable replicas"
      }
     ]
    },
    {
     "title": "Processing latency by write replicas [1m] (bucketed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(devpod_ws_manager_bridge_workspace_instance_update_completed_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(devpod_ws_manager_bridge_workspace_instance_update_completed_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (le))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(devpod_ws_manager_bridge_workspace_instance_update_completed_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (le))",
       "legendFormat": "99th"
      }
     ]
    }
   ]
  },
  {
   "title": "Node.js Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", job=\"ws-manager-bridge\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\", job=\"ws-manager-bridge\", pod=~\"$pod\"}[5m])",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Node.js: Event loop lag (s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{cluster=~\"$cluster\", job=\"ws-manager-bridge\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Node.js: File Handles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_handles_total{cluster=~\"$cluster\", job=\"ws-manager-bridge\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}