packages:
  - name: docker
    type: docker
    config:
      dockerfile: blazedock.Dockerfile
      buildArgs:
        VERSION: ${ipfsKuboVersion}
      image:
        - ${imageRepoBase}/ipfs/kubo:${ipfsKuboVersion}
