packages:
  - name: docker
    type: docker
    config:
      dockerfile: blazedock.Dockerfile
      buildArgs:
        VERSION: ${schedulerExtenderVersion}
      image:
        - ${imageRepoBase}/scheduler-extender:${schedulerExtenderVersion}
