global:
  timestamp: timestamp

jaeger:
  storage: "memory"
  roleBinding: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: devpod.khulnasoft.com/workload_meta
                operator: In
                values:
                  - 'true'
