packages:
  - name: lib
    type: yarn
    srcs:
      - src/**
      - package.json
      - tsconfig.json
    config:
      packaging: library
      dontTest: true
      commands:
        build: ["yarn", "build"]
      yarnLock: ${coreYarnLockBase}/../yarn.lock
      tsconfig: tsconfig.json

  - name: publish
    type: generic
    env:
      - DO_PUBLISH=${publishToNPM}
    argdeps:
      - npmPublishTrigger
    deps:
      - :lib
      - components/devpod-protocol:scripts
    config:
      commands:
        - ["node", "components-devpod-protocol--scripts/publish.js", "${version}", "components-public-api-typescript--lib/package"]
