name: "Deploy Devpod"
description: "Deploys Devpod to an existing preview environment"
inputs:
    name:
        description: "The name of the preview environment to deploy Devpod to"
        required: false
    version:
        description: "The version of Devpod to install"
        required: true
    with_dedicated_emu:
        description: "Dedicated Config"
        required: false
    analytics:
        description: "With analytics"
        required: false
    workspace_feature_flags:
        description: "Workspace feature flags"
        required: false
    image_repo_base:
        description: "The base repository for image"
        required: false
runs:
    using: "docker"
    image: "Dockerfile"
